# Generated by Django 2.2.1 on 2019-05-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('business_type', models.CharField(choices=[('FOOD_TRUCK', 'Food Truck'), ('CONSTRUCTION', 'Construction'), ('OTHER', 'Other')], default='FOOD_TRUCK', max_length=2)),
                ('years', models.PositiveIntegerField()),
            ],
        ),
    ]
